# Generated by Django 5.0 on 2025-11-02 16:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Cpf')),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='E-mail')),
                ('nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('altura', models.IntegerField(validators=[django.core.validators.MaxValueValidator(250)], verbose_name='Altura')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)], verbose_name='Peso')),
                ('esporte', models.CharField(choices=[('FUTEBOL', 'Futebol'), ('BASQUETE', 'Basquete'), ('CORRIDA', 'Corrida')], max_length=20, verbose_name='Esporte')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('local', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('cidade', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)])),
                ('pais', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(2)])),
                ('data', models.DateField()),
                ('esporte', models.CharField(choices=[('FUTEBOL', 'Futebol'), ('BASQUETE', 'Basquete'), ('CORRIDA', 'Corrida')], max_length=20)),
                ('oficial', models.BooleanField(default=True)),
                ('organizador', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('capacidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('assistencias', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('faltas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('cartoes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('minutos_jogados', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('distancia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='analise.atleta')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='analise.evento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
