# Generated by Django 5.0 on 2025-11-06 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atleta',
            old_name='nascionalidade',
            new_name='nacionalidade',
        ),
    ]
